version: '3.8'
services:
  express-app:
    build: 
      context: .
      target: base
      dockerfile: dockerfile
    image: express-ts
    command: npm run dev
    volumes:
      - .:/app
    ports:
      - "5000:5000"
